[build] # Set the default target to ARM Cortex-M (thumbv7m)
target = "thumbv7m-none-eabi"

# Linker arguments for ARM Cortex-M (thumbv7m)
[target.thumbv7m-none-eabi]
runner = """
qemu-sytem-arm \
-cpu cortex-m3 \
-machine lm3s6965evb \
-nographic \
-semihosting-config enable=on,target=native \
-gdb tcp::3333 \
-S \
-kernel \
"""
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=--nmagic"]
